### PR TITLE
Fix crash opening update notification on android

### LINKED ISSUE #1902: Android update notification button crashes the app

### PR DESCRIPTION
**Pull request by myieye**
Resolves #1902

Fixed several problem:
- Needed to use app-launcher instead of window.open
- The platform serialization was inconsistent, so the url lookup wasn't working
- App-launcher wasn't yet available for Android

### CODE REVIEW

File: backend/FwLite/FwLiteMaui/FwLiteMauiKernel.cs [hunk 1]
```diff
@@ -66,6 +66,7 @@ public static void AddFwLiteMauiServices(this IServiceCollection services,
 #endif
 #if ANDROID
         services.Configure<AuthConfig>(config => config.ParentActivityOrWindow = Platform.CurrentActivity);
+        services.AddSingleton<FwLiteShared.Services.IAppLauncher, FwLiteMaui.Services.AppLauncher>();
```
Comment (hahn-kev) [inline backend/FwLite/FwLiteMaui/FwLiteMauiKernel.cs:69]: just add this once and place the call outside an `#if`
