### PR TITLE
Bug/permission issues

### LINKED ISSUE #541: migration leaves the owner of the files as an invalid group
when using rsync to migrate projects it tries to copy over the group `hg` to the new system, however there isn't a group with that name, so it leaves the group as `119`. It doesn't look like this is causing any problems, however this is not the desired outcome of the migration.

- [ ] correct rsync to map the group from hg to www-data
- [ ] correct permissions on all migrated repos

### PR DESCRIPTION
**Pull request by hahn-kev**
closes #541 and #539

We're now setting permissions when creating the root folder for a reset, and we're mapping the hg group to www-data when doing a migration

### CODE REVIEW

File: backend/LexBoxApi/Services/HgService.cs [hunk 1]
```diff
@@ -257,6 +259,7 @@ private static void CopyFilesRecursively(DirectoryInfo source, DirectoryInfo tar
     private static void SetPermissionsRecursively(DirectoryInfo rootDir)
     {
         if (!RuntimeInformation.IsOSPlatform(OSPlatform.Linux)) return;
+        rootDir.UnixFileMode = Permissions;
```
Comment (myieye) [inline backend/LexBoxApi/Services/HgService.cs:262]: We never explicitly set the permissions of `target` in `CopyFilesRecursively`. Should we add that too?

Comment (hahn-kev) [reply backend/LexBoxApi/Services/HgService.cs:261]: yes. Done

**Comment by myieye** [comment]
Nice. Your fix made me realize that you can also delete line 265.

**Review by myieye — APPROVED** [review]
