### PR TITLE
Ensure senses are created before adding complex-form-components

### LINKED ISSUE #1944: Project sync blocked: 'FOREIGN KEY constraint failed'
**Describe the bug**

Trace:
https://ui.honeycomb.io/sil-language-forge/environments/prod/result/g3xQxazrb5f/trace/FtuBHrU2U42?fields[]=s_serviceName&fields[]=s_name&fields[]=c_app.project_id&fields[]=c_app.project_code&span=2cc3b90d308ebea7

> Microsoft.EntityFrameworkCore.DbUpdateException: Error saving snapshots: An error occurred while saving the entity changes. See the inner exception for details.
> ComplexFormComponent {Id: 69cef642-09ae-4dde-8ad8-90b8ee1594b7} Added FK {ComplexFormEntryId: 48f9f242-5430-4411-9b7b-45bed6cd5a35} FK {ComponentEntryId: efa474fe-0e2f-4e7c-91c2-9a9b6728d5cb} FK {ComponentSenseId: 14d472e0-3c18-4e09-9295-585e2ac9efd9} FK {SnapshotId: 10894b81-beae-4ff5-83a6-e5485f12766b}
>  ---> Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
>  ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
>    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
>    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
>    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
>    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChangesAsync(IList`1 entries, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
>    at SIL.Harmony.Db.CrdtRepository.AddSnapshots(IEnumerable`1 snapshots) in /harmony/src/SIL.Harmony/Db/CrdtRepository.cs:line 316
>    --- End of inner exception stack trace ---
>    at SIL.Harmony.Db.CrdtRepository.AddSnapshots(IEnumerable`1 snapshots) in /harmony/src/SIL.Harmony/Db/CrdtRepository.cs:line 323
>    at SIL.Harmony.SnapshotWorker.UpdateSnapshots(Commit oldestAddedCommit, Commit[] newCommits) in /harmony/src/SIL.Harmony/SnapshotWorker.cs:line 58
>    at SIL.Harmony.DataModel.UpdateSnapshots(CrdtRepository repo, Commit oldestAddedCommit, Commit[] newCommits) in /harmony/src/SIL.Harmony/DataModel.cs:line 215
>    at SIL.Harmony.DataModel.Add(Commit commit) in /harmony/src/SIL.Harmony/DataModel.cs:line 123
>    at SIL.Harmony.DataModel.Add(Commit commit) in /harmony/src/SIL.Harmony/DataModel.cs:line 128
>    at SIL.Harmony.DataModel.Add(Commit commit) in /harmony/src/SIL.Harmony/DataModel.cs:line 128
>    at SIL.Harmony.DataModel.AddChanges(Guid clientId, IEnumerable`1 changes, Guid commitId, CommitMetadata commitMetadata) in /harmony/src/SIL.Harmony/DataModel.cs:line 98
>    at SIL.Harmony.DataModel.AddChange(Guid clientId, IChange change, Guid commitId, CommitMetadata commitMetadata) in /harmony/src/SIL.Harmony/DataModel.cs:line 66
>    at LcmCrdt.CrdtMiniLcmApi.AddChange(IChange change) in /FwLite/LcmCrdt/CrdtMiniLcmApi.cs:line 52
>    at LcmCrdt.CrdtMiniLcmApi.CreateComplexFormComponent(ComplexFormComponent complexFormComponent, BetweenPosition`1 between) in /FwLite/LcmCrdt/CrdtMiniLcmApi.cs:line 308
>    at LcmCrdt.CrdtMiniLcmApi.CreateComplexFormComponent(ComplexFormComponent complexFormComponent, BetweenPosition`1 between) in /FwLite/LcmCrdt/CrdtMiniLcmApi.cs:line 315
>    at MiniLcm.SyncHelpers.EntrySync.ComplexFormComponentsDiffApi.Add(ComplexFormComponent after, BetweenPosition between) in /FwLite/MiniLcm/SyncHelpers/EntrySync.cs:line 232
>    at MiniLcm.SyncHelpers.DiffCollection.DiffOrderable[T](IList`1 before, IList`1 after, IOrderableCollectionDiffApi`1 diffApi) in /FwLite/MiniLcm/SyncHelpers/DiffCollection.cs:line 148
>    at MiniLcm.SyncHelpers.EntrySync.SyncComplexFormComponents(Entry afterEntry, IList`1 beforeComponents, IList`1 afterComponents, IMiniLcmApi api) in /FwLite/MiniLcm/SyncHelpers/EntrySync.cs:line 60
>    at MiniLcm.SyncHelpers.EntrySync.Sync(Entry beforeEntry, Entry afterEntry, IMiniLcmApi api) in /FwLite/MiniLcm/SyncHelpers/EntrySync.cs:line 24
>    --- End of inner exception stack trace ---
>    at MiniLcm.SyncHelpers.EntrySync.Sync(Entry beforeEntry, Entry afterEntry, IMiniLcmApi api) in /FwLite/MiniLcm/SyncHelpers/EntrySync.cs:line 32
>    at MiniLcm.SyncHelpers.DiffCollection.DiffAddThenUpdate[T,TId](IList`1 before, IList`1 after, CollectionDiffApi`2 diffApi) in /FwLite/MiniLcm/SyncHelpers/DiffCollection.cs:line 76
>    at MiniLcm.SyncHelpers.EntrySync.Sync(Entry[] beforeEntries, Entry[] afterEntries, IMiniLcmApi api) in /FwLite/MiniLcm/SyncHelpers/EntrySync.cs:line 13
>    at FwLiteProjectSync.CrdtFwdataProjectSyncService.Sync(IMiniLcmApi crdtApi, IMiniLcmApi fwdataApi, Boolean dryRun, Int32 entryCount, ProjectSnapshot projectSnapshot) in /FwLite/FwLiteProjectSync/CrdtFwdataProjectSyncService.cs:line 92
>    at FwLiteProjectSync.CrdtFwdataProjectSyncService.Sync(IMiniLcmApi crdtApi, FwDataMiniLcmApi fwdataApi, Boolean dryRun) in /FwLite/FwLiteProjectSync/CrdtFwdataProjectSyncService.cs:line 39
>    at FwHeadless.Services.SyncWorker.ExecuteSync(CancellationToken stoppingToken) in /FwHeadless/Services/SyncHostedService.cs:line 170
>    at FwHeadless.Services.SyncHostedService.ExecuteAsync(CancellationToken stoppingToken) in /FwHeadless/Services/SyncHostedService.cs:line 33

### PR DESCRIPTION
**Pull request by myieye**
Fixes #1944

### CODE REVIEW

File: backend/FwLite/MiniLcm/SyncHelpers/EntrySync.cs [hunk 1]
```diff
@@ -97,15 +97,27 @@ private static async Task<int> SensesSync(Guid entryId,
...
             var entryWithoutEntryRefs = afterEntry.WithoutEntryRefs();
             var changes = await Add(entryWithoutEntryRefs);
             return (changes, entryWithoutEntryRefs);
         }
 
+        public override async Task<(int, Entry)> ReplaceWithoutReferencesAndGet(Entry beforeEntry, Entry afterEntry)
+        {
+            //same as AddAndGet, but for already existing entries, because they
+            //might have new entities (e.g. senses) in their hierarchy that other entries reference
+            var beforeEntryWithoutEntryRefs = beforeEntry.WithoutEntryRefs();
```
Comment (myieye) [inline backend/FwLite/MiniLcm/SyncHelpers/EntrySync.cs:113]: @hahn-kev there's a decent amount of object churn in here. What do you think? It's nice having everything be so generic, but we could make it more specific and explicit and only sync senses.

Comment (hahn-kev) [reply backend/FwLite/MiniLcm/SyncHelpers/EntrySync.cs:113]: yeah I think it would make more sense to just be specific, it's hard to understand what's going on here right now.

Comment (hahn-kev) [reply backend/FwLite/MiniLcm/SyncHelpers/EntrySync.cs:113]: also the method `WithoutEntryRefs` is kinda a lie, it includes Sense refs for example.

File: backend/FwLite/MiniLcm/SyncHelpers/EntrySync.cs [hunk 2]
```diff
@@ -34,6 +60,26 @@ public static async Task<int> Sync(Entry beforeEntry, Entry afterEntry, IMiniLcm
         }
     }
 
+    /// <summary>
+    /// Syncs only the complex forms and components of the before and after entries.
+    /// If before is null it is assumed to have already been created and have NO complex forms or components.
+    /// </summary>
+    public static async Task<int> SyncComplexFormsAndComponents(Entry? beforeEntry, Entry afterEntry, IMiniLcmApi api)
```
Comment (myieye) [inline backend/FwLite/MiniLcm/SyncHelpers/EntrySync.cs:67]: @hahn-kev So, currently I'm just passing in null here for added entries.

It's the cheapest solution, but  a bit weird, because it assumes you're using it correctly (i.e. you've created the entry in the db and for some reason you just don't have it). It works, because we don't actually need anything from the entry if it's new.

The alternative is the old Add-And-Get approach. I.e. we somehow get newly created entries (created via `SyncWithout...`) into the list of `beforeEntries`. Then we could make the diff API for syncing Complex forms throw an exception if Add is called. We could either return all the added ones from the Diff collection method or collect them in the EntriesDiffApi. We'd create a few more collections, but...I guess it's pretty minimal: just one or two. So, that's probably better than the approach I've taken.

What do you think?

All in all I think this PR has taken a good direction. 👍

File: backend/FwLite/MiniLcm/Models/Entry.cs [hunk 3]
```diff
@@ -2,6 +2,8 @@ namespace MiniLcm.Models;
 
 public record Entry : IObjectWithId<Entry>
 {
+    public static readonly Entry Empty = new();
```
Comment (hahn-kev) [inline backend/FwLite/MiniLcm/Models/Entry.cs:5]: I don't love this because you then need to write code which detects if you have an empty entry and handle that, for example `CreateEntry(Entry.Empty)` should throw. If this does stick around then it should be changed to return a new object because `Entry` is mutable. So an empty entry could accidentally be modified and now everyone gets a non empty entry.

File: backend/FwLite/MiniLcm/SyncHelpers/EntrySync.cs (hunk 2 above)
Comment (hahn-kev) [reply backend/FwLite/MiniLcm/SyncHelpers/EntrySync.cs:67]: Hum, yeah that's kinda messy. Considering the `CreateEntry` api returns the created entry (not the one passed in), I think that shouldn't be terribly hard, but it's not very clean either.

After looking at the rest of the code I think I would prefer that this doesn't take null and uses the Add and Get approach.
