### PR TITLE
Managers can edit projects (round 2)

### LINKED ISSUE #17: Managers can edit projects
They need to be able to do the following:

- #69 (out of scope for this issue)
- [x] add members
- [x] remove members
- [ ] change member role (currently broken)
- [x] change name and description (but not code)

### PR DESCRIPTION
**Pull request by myieye**
Fixes #17 (and actually completes it)

Managers and admin can now change member roles, but not their own roles (except admins 🤷).

Managers can manager system admin members. Seems fine to me, because system admins shouldn't have to be members in order to do tech support.

My auto formatter had quite a bit of fun here, but I think it fixed a lot of bad formatting, so I'm just hoping that everything it did is compliant with other people's formatters. I'm not really sure how that's configured.

### CODE REVIEW

File: frontend/src/lib/components/Badges/Badge.svelte
Comment (longrunningprocess) [inline frontend/src/lib/components/Badges/Badge.svelte:1]: this looks much better, thank you

File: frontend/src/lib/components/Badges/BadgeButton.svelte
Comment (longrunningprocess) [inline frontend/src/lib/components/Badges/BadgeButton.svelte:1]: yes, thank you for designing out the `if`, much appreciated!

File: frontend/src/lib/components/EditableText.svelte [hunk 1]
```diff
@@ -1,59 +1,58 @@
...
 	import IconButton from './IconButton.svelte';
-	import { Form, lexSuperForm, lexSuperValidate } from '$lib/forms';
 
 	export let value: string | undefined | null = undefined;
 	export let disabled = false;
 	export let saveHandler: (newValue: string) => Promise<unknown>;
 	export let placeholder: string | undefined = undefined;
 	export let multiline = false;
 	export let validation: ZodString | undefined = undefined;
+	export const id = crypto.randomUUID().split('-').at(-1) as string;
```
Comment (longrunningprocess) [inline frontend/src/lib/components/EditableText.svelte:12]: I might suggest this become a project-wide util.

File: frontend/src/lib/forms/index.ts [hunk 2]
```diff
@@ -1,51 +1,51 @@
...
+import type { AnyZodObject } from 'zod';
+import Button from './Button.svelte';
+import Form from './Form.svelte';
+import Input from './Input.svelte';
+import ProtectedForm, { type Token } from './ProtectedForm.svelte';
+import Select from './Select.svelte';
 
 //we've got to wrap this in our own version because we're not using the server side component, which this expects
-export function lexSuperForm<S extends ZodValidation<AnyZodObject>>(schema: S, onSubmit: NonNullable<FormOptions<S, string>["onUpdate"]>, options: Omit<FormOptions<S, string>, 'validators'> = {}): SuperForm<S, string> {
+export function lexSuperForm<S extends ZodValidation<AnyZodObject>>(
```
Comment (longrunningprocess) [inline frontend/src/lib/forms/index.ts:14]: nice, I seeing these functions here!

File: frontend/src/routes/project/[project_code]/+page.ts [hunk 3]
```diff
@@ -1,147 +1,192 @@
...
+	if (result.error) throw new Error(result.error.message);
+	event.depends(`project:${result.data?.projects[0]?.id}`);
+	return {
+		project: result.data?.projects[0],
+		log: logsample,
+		code: projectCode,
+	};
+}
+
+export async function _addProjectMember(input: AddProjectMemberInput) {
```
Comment (longrunningprocess) [inline frontend/src/routes/project/[project_code]/+page.ts:63]: I'm still not crazy about exporting stuff from here that not part of the convention for this file type...

**Review by longrunningprocess — APPROVED** [review]

File: frontend/src/lib/components/Badges/Badge.svelte [hunk 4]
```diff
@@ -1,23 +1,12 @@
 <script lang="ts">
-	import { Badge } from '.';
-
 	export let type = '';
```
Comment (hahn-kev) [inline frontend/src/lib/components/Badges/Badge.svelte:2]: I should have mentioned this in the last PR, but could we specify the valid strings here? in this case it's really just going to be injected into the class so you can use anything, but just for usability for a dev can we specify the valid strings here?

File: frontend/src/lib/components/modals/Modal.svelte [hunk 5]
```diff
@@ -17,7 +17,7 @@
 
 	let dialogResponse = writable<DialogResponse | null>(null);
 	let open = writable(false);
-	$: closing = $dialogResponse !== null && open;
+	$: closing = $dialogResponse !== null && $open;
```
Comment (hahn-kev) [inline frontend/src/lib/components/modals/Modal.svelte:20]: good catch!

File: frontend/src/lib/forms/UserRoleSelect.svelte [hunk 6]
```diff
@@ -0,0 +1,15 @@
+<script lang="ts">
+	import { ProjectRole } from '$lib/gql/graphql';
+	import t from '$lib/i18n';
+
+	import { Select } from '.';
+
+    export let id = 'role';
```
Comment (hahn-kev) [inline frontend/src/lib/forms/UserRoleSelect.svelte:7]: minor indenting issue here

File: backend/LexBoxApi/GraphQL/LexMutations.cs [hunk 7]
```diff
@@ -42,12 +43,27 @@ public LexMutations(LoggedInContext loggedInContext)
...
+        return projectUser;
+    }
+
     [Error<NotFoundException>]
     [Error<DbError>]
     [UseMutationConvention]
     public async Task<Project> ChangeProjectName(ChangeProjectNameInput input,
         LexBoxDbContext dbContext)
     {
+        if (input.Name.IsNullOrEmpty()) throw new RequiredException("Project name cannot be empty");
```
Comment (hahn-kev) [inline backend/LexBoxApi/GraphQL/LexMutations.cs:65]: because you're throwing a new exception here you should add an attribute for it on this method, just like the  NotFoundException, it's so that we can tell HotChocolate which exceptions are errors and should be returned to the user vs not.

File: frontend/src/lib/forms/index.ts [hunk 8]
```diff
@@ -1,51 +1,51 @@
...
+		onResult: async (event) => {
 			const messageBefore = get(sf.message);
 			await options.onResult?.(event);
-			const result = event.result as ActionResult<{form: Validation<S>}>;
-			if (result.type == "success" && result.data) {
-				await onSubmit({form: result.data.form, cancel: event.cancel});
-				// sometimes during submit the message is set using the store that's returned from setup, 
+			const result = event.result as ActionResult<{ form: Validation<S> }>;
+			if (result.type == 'success' && result.data) {
+				await onSubmit({ form: result.data.form, formEl: event.formEl, cancel: event.cancel });
```
Comment (hahn-kev) [inline frontend/src/lib/forms/index.ts:30]: thanks for fixing that :)

File: frontend/src/routes/project/[project_code]/+page.svelte [hunk 9]
```diff
@@ -34,21 +38,34 @@
...
-				validation={projectNameValidation}
-				saveHandler={(newValue) => _changeProjectName({ projectId: _project.id, name: newValue })}
-			/>
+		<div class="space-y-2">
+			<div class="text-3xl flex items-center gap-3 flex-wrap">
+				<span>{$t('project_page.project')}:</span>
+				<EditableText
+					disabled={!canManage}
+					bind:value={project.name}
+					validation={projectNameValidation}
```
Comment (hahn-kev) [inline frontend/src/routes/project/[project_code]/+page.svelte:65]: idea for later might be to add a `required` attribute that would do the same, optionally accepting the error text.

File: frontend/src/routes/project/[project_code]/+page.svelte [hunk 10]
```diff
@@ -60,23 +77,22 @@
...
 			</div>
 			<div class="text-lg">{$t('project_page.description')}:</div>
 			<span>
 				<EditableText
-					value={project.description}
+					bind:value={project.description}
 					disabled={!canManage}
-					saveHandler={(newValue) =>
-						_changeProjectDescription({ projectId: _project.id, description: newValue })}
+					saveHandler={updateProjectDescription}
```
Comment (hahn-kev) [inline frontend/src/routes/project/[project_code]/+page.svelte:93]: thank you! Much easier to parse and understand now.

File: frontend/src/routes/project/[project_code]/+page.ts [hunk 11]
```diff
@@ -1,147 +1,192 @@
...
+				}
+			`),
+			{ projectCode },
+		)
+		.toPromise();
+	if (result.error) throw new Error(result.error.message);
+	event.depends(`project:${result.data?.projects[0]?.id}`);
+	return {
+		project: result.data?.projects[0],
+		log: logsample,
```
Comment (hahn-kev) [inline frontend/src/routes/project/[project_code]/+page.ts:58]: @rmunn can we remove the sample log data now?

File: frontend/src/routes/project/[project_code]/AddProjectMember.svelte [hunk 12]
```diff
@@ -16,26 +17,27 @@
...
+		modal.submitModal(),
+	);
 	async function openModal(): Promise<void> {
-		if (await modal.openModal() === DialogResponse.Cancel) return;
-		const result = await _addProjectUser({ projectId, userEmail: $form.email, role: $form.role });
+		if ((await modal.openModal()) === DialogResponse.Cancel) return;
+		const result = await _addProjectMember({ projectId, userEmail: $form.email, role: $form.role });
 		if (result.error) {
-			$message = result.error.message + ' ' + count++;
+			$message = result.error.message;
```
Comment (hahn-kev) [inline frontend/src/routes/project/[project_code]/AddProjectMember.svelte:27]: thank you, I probably left that count in from some debugging

File: frontend/src/routes/project/[project_code]/ChangeMemberRoleModal.svelte [hunk 13]
```diff
@@ -0,0 +1,56 @@
...
+	import Form from '$lib/forms/Form.svelte';
+	import UserRoleSelect from '$lib/forms/UserRoleSelect.svelte';
+	import { ProjectRole } from '$lib/gql/graphql';
+	import t from '$lib/i18n';
+	import { z } from 'zod';
+	import { _changeProjectMemberRole } from './+page';
+
+	export let projectId: string;
+
+	let _name: string;
```
Comment (hahn-kev) [inline frontend/src/routes/project/[project_code]/ChangeMemberRoleModal.svelte:13]: any reason this is prefixed with an underscore?

File: frontend/src/routes/project/[project_code]/ChangeMemberRoleModal.svelte [hunk 14]
```diff
@@ -0,0 +1,56 @@
...
+
+	export async function open(member: { userId: string; name: string }): Promise<void> {
```
Comment (hahn-kev) [inline frontend/src/routes/project/[project_code]/ChangeMemberRoleModal.svelte:15]: good implementation of the modal. Man is it a pain when combined with a form, even I have a little trouble tracking it. I wonder if it would be better with a ModalForm that wraps that up so you can just use it like a modal? Just a thought I had, no action required.

**Review by hahn-kev — APPROVED** [review]
looks good to me!

File: frontend/src/routes/project/[project_code]/+page.ts (hunk 3 above)
Comment (myieye) [reply frontend/src/routes/project/[project_code]/+page.ts:63]: 👍 we'll discuss this [soon](https://github.com/sillsdev/languageforge-lexbox/pull/65#discussion_r1206322550)

File: frontend/src/routes/project/[project_code]/ChangeMemberRoleModal.svelte (hunk 13 above)
Comment (myieye) [reply frontend/src/routes/project/[project_code]/ChangeMemberRoleModal.svelte:13]: For some reason I thought there was a naming collision 😆
