### PR TITLE
Test: 348 make Playwright detect 500s

### LINKED ISSUE #348: Write Playwright test that verifies an error is shown when the server returns a 500
Both email workflow tests in the attached traces failed, because the API was broken and returning 500s
1) The verify email link didn't work
2) Clicking "Reset password" didn't work

Neither trace shows that an error page was displayed, which is unexpected and unhelpful, because we had to dig through the network log to find out that the app was actually broken.

For 1 we somehow want to teach the API to return an error page.
For 2 it's puzzling that no error was shown. But it should be easy to reproduce (just make sure [the fix](https://github.com/sillsdev/languageforge-lexbox/commit/319af51504401c9b34c871a96ab3c53dfe4c3b2c) isn't in your build and do what the test did). Then maybe we want to create a test API endpoint for this purpose and maybe access it from a new sandbox page.

[playwright-traces.zip](https://github.com/sillsdev/languageforge-lexbox/files/13118166/playwright-traces.zip) (actually a 7z file - password protected with our current staging password)

### LINKED ISSUE #349: catch fetch 500 errors in svelte and throw exceptions
we want to show an error dialog to the user which they can then report to us

### PR DESCRIPTION
**Pull request by myieye**
Resolves #348
Resolves #349

Status code handling is further improved in a draft PR (#357) that is waiting for this one to be merged.

Here's what the output looks like for the tests that were getting 500s. It's still a lot to parse, but at least there's a 500 in there:

<details><summary>EmailWorkflowTests.RegisterVerifyUpdateVerifyEmailAdress</summary>
<p>
[xUnit.net 00:00:40.47]     Testing.Browser.EmailWorkflowTests.RegisterVerifyUpdateVerifyEmailAdre
ss [FAIL]
  Failed Testing.Browser.EmailWorkflowTests.RegisterVerifyUpdateVerifyEmailAdress [37 s]
  Error Message:
   System.AggregateException : One or more errors occurred. (Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for navigation to "/user" until "NetworkIdle"
============================================================) (One or more errors occurred. (Unexp
ected response: Internal Server Error (500). URL: http://localhost/api/login/verifyEmail?jwt=*****
&returnTo=%2Fuser%3FemailResult%3DverifiedEmail&email=54fb1b67-e426-4367-928a-f863514b1159@mailina
tor.com.))
---- System.TimeoutException : Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for navigation to "/user" until "NetworkIdle"
============================================================
-------- System.TimeoutException : Timeout 30000ms exceeded.
---- System.AggregateException : One or more errors occurred. (Unexpected response: Internal Serve
r Error (500). URL: http://localhost/api/login/verifyEmail?jwt=*****&returnTo=%2Fuser%3FemailResul
t%3DverifiedEmail&email=54fb1b67-e426-4367-928a-f863514b1159@mailinator.com.)
-------- Testing.Browser.Base.UnexpectedResponseException : Unexpected response: Internal Server E
rror (500). URL: http://localhost/api/login/verifyEmail?jwt=*****&returnTo=%2Fuser%3FemailResult%3
DverifiedEmail&email=54fb1b67-e426-4367-928a-f863514b1159@mailinator.com.
  Stack Trace:

----- Inner Stack Trace #1 (System.TimeoutException) -----
   at Microsoft.Playwright.Core.Waiter.WaitForPromiseAsync[T](Task`1 task, Action dispose) in /_/s
rc/Playwright/Core/Waiter.cs:line 219
   at Microsoft.Playwright.Core.Frame.WaitForNavigationInternalAsync(Waiter waiter, String url, Fu
nc`2 urlFunc, Regex urlRegex, String urlString, Nullable`1 waitUntil) in /_/src/Playwright/Core/Fr
ame.cs:line 257
   at Microsoft.Playwright.Core.Frame.RunAndWaitForNavigationAsync(Func`1 action, FrameRunAndWaitF
orNavigationOptions options) in /_/src/Playwright/Core/Frame.cs:line 225
   at Testing.Browser.Page.BasePage`1.WaitFor() in D:\code\languageforge-lexbox\backend\Testing\Br
owser\Page\BasePage.cs:line 39
   at Testing.Browser.EmailWorkflowTests.RegisterVerifyUpdateVerifyEmailAdress() in D:\code\langua
geforge-lexbox\backend\Testing\Browser\EmailWorkflowTests.cs:line 31
   at Testing.Browser.EmailWorkflowTests.RegisterVerifyUpdateVerifyEmailAdress() in D:\code\langua
geforge-lexbox\backend\Testing\Browser\EmailWorkflowTests.cs:line 63
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at Microsoft.Playwright.Helpers.TaskHelper.<>c__DisplayClass2_0.<WithTimeout>b__0() in /_/src/P
laywright/Helpers/TaskHelper.cs:line 73
   at Microsoft.Playwright.Helpers.TaskHelper.WithTimeout(Task task, Func`1 timeoutAction, TimeSpa
n timeout, CancellationToken cancellationToken) in /_/src/Playwright/Helpers/TaskHelper.cs:line 10
9
   at Microsoft.Playwright.Core.Waiter.WaitForPromiseAsync[T](Task`1 task, Action dispose) in /_/s
rc/Playwright/Core/Waiter.cs:line 211
----- Inner Stack Trace #2 (System.AggregateException) -----
   at Testing.Browser.Base.PageTest.DisposeAsync() in D:\code\languageforge-lexbox\backend\Testing
\Browser\Base\PageTest.cs:line 91
----- Inner Stack Trace -----
</p>
</details>

<details><summary>EmailWorkflowTests.ForgotPassword</summary>
<p>
[xUnit.net 00:00:43.78]     Testing.Browser.EmailWorkflowTests.ForgotPassword [FAIL]
  Failed Testing.Browser.EmailWorkflowTests.ForgotPassword [40 s]
  Error Message:
   System.AggregateException : One or more errors occurred. (response.Status
    should be
200
    but was
403

Additional Info:
    code was 403 (Forbidden)) (One or more errors occurred. (Unexpected response: Internal Server
Error (500). URL: http://localhost/api/login/resetPassword.))
---- Shouldly.ShouldAssertException : response.Status
    should be
200
    but was
403

Additional Info:
    code was 403 (Forbidden)
---- System.AggregateException : One or more errors occurred. (Unexpected response: Internal Serve
r Error (500). URL: http://localhost/api/login/resetPassword.)
-------- Testing.Browser.Base.UnexpectedResponseException : Unexpected response: Internal Server E
rror (500). URL: http://localhost/api/login/resetPassword.
  Stack Trace:

----- Inner Stack Trace #1 (Shouldly.ShouldAssertException) -----
   at Testing.Browser.Util.HttpUtils.ExecuteGql(IPage page, String gql, Boolean expectGqlError) in
 D:\code\languageforge-lexbox\backend\Testing\Browser\Util\HttpUtils.cs:line 16
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task tas
k)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Testing.Browser.Page.TempUserDashboardPage.DisposeAsync() in D:\code\languageforge-lexbox\ba
ckend\Testing\Browser\Page\TempUserDashboardPage.cs:line 17
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task tas
k)
   at Testing.Browser.EmailWorkflowTests.ForgotPassword() in D:\code\languageforge-lexbox\backend\
Testing\Browser\EmailWorkflowTests.cs:line 96
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task tas
k)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task tas
k)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task tas
k)
----- Inner Stack Trace #2 (System.AggregateException) -----
   at Testing.Browser.Base.PageTest.DisposeAsync() in D:\code\languageforge-lexbox\backend\Testing
\Browser\Base\PageTest.cs:line 91
----- Inner Stack Trace -----
</p>
</details>

Here's the error dialog that will now be shown if "Reset password" gets a 500 response:
image

### CODE REVIEW

File: backend/Testing/Browser/Base/PageTest.cs [hunk 1]
```diff
@@ -39,6 +59,19 @@ await Context.Tracing.StartAsync(new()
...
+        {
+            if (response.Status >= (int)HttpStatusCode.InternalServerError)
+            {
+                DeferredExceptions.Add(new UnexpectedResponseException(response));
+            }
+        };
+
+        Context.Request += (_, request) =>
+        {
+            Console.WriteLine(request.IsNavigationRequest);
```
Comment (hahn-kev) [inline backend/Testing/Browser/Base/PageTest.cs:73]: I don't think this will show up properly in an xunit test. Was this left in by accident?

File: backend/Testing/Browser/Base/PageTest.cs [hunk 2]
```diff
@@ -26,6 +31,21 @@ public PageTest()
     public ILocatorAssertions Expect(ILocator locator) => Assertions.Expect(locator);
     public IPageAssertions Expect(IPage page) => Assertions.Expect(page);
     public IAPIResponseAssertions Expect(IAPIResponse response) => Assertions.Expect(response);
+    /// <summary>
+    /// Consumes a defferred exception that was "thrown" in a sub-thread, and returns it
+    /// or throws if no exception of the given type is found.
+    /// </summary>
+    public Exception ExpectDeferredException<TException>() where TException : Exception
```
Comment (hahn-kev) [inline backend/Testing/Browser/Base/PageTest.cs:38]: we might as well return `TException` here as we know that it's that type. That being said, right now you just need to know that `UnexpectedResponseException` is the only type that's supported (though you could just use Exception), is there a better way to do it? Maybe for now we just remove the generic and we can change that later if we have other exception types we care about.

File: backend/Testing/Browser/Base/PageTest.cs [hunk 3]
```diff
@@ -26,6 +31,21 @@ public PageTest()
...
+    {
+        var exception = DeferredExceptions.FirstOrDefault(e => e is TException);
```
Comment (hahn-kev) [inline backend/Testing/Browser/Base/PageTest.cs:40]: should we use single? would it be an error if there were 2 exceptions when we really only expected one?

File: backend/Testing/Browser/Base/UnexpectedResponseException.cs [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+    public UnexpectedResponseException(IResponse response)
+    : this(response.StatusText, response.Status, response.Url)
+    {
+    }
+
+    public UnexpectedResponseException(string statusText, int statusCode, string url)
+    : base($"Unexpected response: {statusText} ({statusCode}). URL: {MaskUrl(url)}.") { }
+
+    [GeneratedRegex("[A-Za-z0-9-_]{10,}\\.[A-Za-z0-9-_]{20,}\\.[A-Za-z0-9-_]{10,}")]
+    private static partial Regex JwtRegex();
```
Comment (hahn-kev) [inline backend/Testing/Browser/Base/UnexpectedResponseException.cs:22]: nice use of the new regex generator

**Review by hahn-kev — COMMENTED** [review]
Nice work, I like storing the errors and throwing them later if none were expected.

File: backend/Testing/Browser/Base/PageTest.cs (hunk 1 above)
Comment (myieye) [reply backend/Testing/Browser/Base/PageTest.cs:73]: Yes, I didn't intend to check that in. I'll remove it.

File: backend/Testing/Browser/Base/UnexpectedResponseException.cs (hunk 4 above)
Comment (myieye) [reply backend/Testing/Browser/Base/UnexpectedResponseException.cs:22]: VS Code wrote that 😉

File: backend/Testing/Browser/Base/PageTest.cs (hunk 3 above)
Comment (myieye) [reply backend/Testing/Browser/Base/PageTest.cs:40]: I don't think I'll just Single though, because I'd like a more expect-like error message.

File: backend/Testing/Browser/Base/PageTest.cs (hunk 2 above)
Comment (myieye) [reply backend/Testing/Browser/Base/PageTest.cs:38]: OK. I'll limit it for now.

Comment (hahn-kev) [reply backend/Testing/Browser/Base/PageTest.cs]: this still isn't resolved

File: backend/Testing/Browser/Base/PageTest.cs [hunk 5]
```diff
@@ -26,6 +31,23 @@ public PageTest()
...
     public IPageAssertions Expect(IPage page) => Assertions.Expect(page);
     public IAPIResponseAssertions Expect(IAPIResponse response) => Assertions.Expect(response);
+    /// <summary>
+    /// Consumes a deferred exception that was "thrown" in a sub-thread, and returns it
+    /// or throws if no exception of the given type is found.
+    /// </summary>
+    public UnexpectedResponseException ExpectDeferredException()
+    {
+        DeferredExceptions.Count.ShouldBeGreaterThan(0, "Expected a deferred exception, but none were found.");
+        DeferredExceptions.Count.ShouldBe(1, $"Expected a deferred exception, but {DeferredExceptions.Count} were found: {new AggregateException(DeferredExceptions)}.");
```
Comment (hahn-kev) [inline backend/Testing/Browser/Base/PageTest.cs:41]: there's a `ShouldNotBeEmpty` and `ShouldHaveSingleItem` that would better suite here as the error messages will show what values are in the list instead.

**Review by hahn-kev — APPROVED** [review]
