### PR TITLE
Don't lose media files when there's an S&R rollback

### LINKED ISSUE #1870: Chorus rollbacks lose media files
**Describe the bug**
If there's a merge conflict that chorus can't resolve, then it will rollback the changes, when that rollback happens any new media files will be lost.

**To Fix**
In order to fix this we are going to commit files when they are uploaded. We **will not** sync the hg repo as part of an upload, we will just commit it to the repo in fw-headless. The commit message should reference what's happening eg "add file.mp3" or remove etc.

### PR DESCRIPTION
**Pull request by hahn-kev**
closes #1870 

I also refactored our code saving media files into the MediaFileService and then wrote some tests for the new method including one ensuring a rollback doesn't delete files.

### CODE REVIEW

File: backend/Testing/FwHeadless/MediaFileServiceTests.cs [hunk 1]
```diff
@@ -143,6 +149,101 @@ public async Task Sync_PreExistingFilesArePreserved()
...
+        Directory.GetFiles(directoryName).Should().Contain(filePath);
+
+        //make a commit which would be rolled back by S&R during a conflict
+        var conflictFile = Path.Join(_cache.LangProject.LinkedFilesRootDir, "conflict.txt");
+        await File.WriteAllTextAsync(conflictFile, "test");
+        HgRunner.Run("hg commit --message \"test commit\" --addremove", directoryName, 5, new NullProgress());
+
+        var rev = int.Parse(_hgRepository.GetHeads().Single().Number.LocalRevisionNumber) - 1;
+        //simulate rollback as seen here: https://github.com/sillsdev/chorus/blob/af6e5c0e97758aef00bd2104b6c1ccf5719798ef/src/LibChorus/sync/Synchronizer.cs#L574
+        _hgRepository.RollbackWorkingDirectoryToRevision(rev.ToString());
```
Comment (hahn-kev) [inline backend/Testing/FwHeadless/MediaFileServiceTests.cs:201]: @jasonleenaylor I'm just guessing here, this doesn't match exactly because I'm taking the head and subtracting one in order to rollback what I'm assuming would be the commit which happens locally before any changes are pulled? But I'm not sure what the difference is between this and whats happening during a conflict.
