### PR TITLE
Do not throw exceptions for empty model number

### LINKED ISSUE #1242: HgService.GetModelVersionOfFlexProject will throw if the project is empty
**Describe the bug**
When clicking the reload Model version button on the project page there's an error 
trace: https://ui.honeycomb.io/sil-language-forge/environments/staging/trace/bzrkhTWCFZk?fields[]=s_name&fields[]=s_serviceName&span=d43fa5e5b42823da

**To Reproduce**

1. create a new project
2. don' t upload anything so the repo is empty
3. click refresh model version
4. see error about json parsing error

**Expected behavior**
nothing should happen, the model version should be left as null

### PR DESCRIPTION
**Pull request by rmunn**
Fix #1242.

If a project is empty, the FLEx model version command returns an empty string. HgService.GetModelVersionOfFlexProject should not throw an exception in such cases, but simply return null meaning "can't find the FLEx model".

### CODE REVIEW

File: backend/LexBoxApi/Services/HgService.cs [hunk 1]
```diff
@@ -271,8 +271,19 @@ private string[] GetWsList(System.Xml.XmlElement root, string tagName)
     {
         var result = await ExecuteHgCommandServerCommand(code, "flexmodelversion", token);
         var text = await result.ReadAsStringAsync(token);
-        var json = JsonDocument.Parse(text);
-        return json.RootElement.GetProperty("modelversion").GetInt32();
+        if (string.IsNullOrEmpty(text)) return null;
```
Comment (myieye) [inline backend/LexBoxApi/Services/HgService.cs:274]: I feel like this would be a minor improvement.
```suggestion
        if (string.IsNullOrWhitespace(text)) return null;
```

File: backend/LexBoxApi/Services/HgService.cs [hunk 2]
```diff
@@ -271,8 +271,19 @@ private string[] GetWsList(System.Xml.XmlElement root, string tagName)
...
+        try
+        {
+            var json = JsonDocument.Parse(text);
+            if (json.RootElement.GetProperty("modelversion").TryGetInt32(out int version)) return version;
```
Comment (hahn-kev) [inline backend/LexBoxApi/Services/HgService.cs:278]: `GetProperty` will throw a `KeyNotFoundException` if it's not found, it looks like there's a try get property method as well

**Review by hahn-kev — CHANGES_REQUESTED** [review]
lots of edge cases here

File: backend/LexBoxApi/Services/HgService.cs (hunk 1 above)
Comment (rmunn) [reply backend/LexBoxApi/Services/HgService.cs]: Done in fd3d2174. I was thinking there's no need for that, but then I realized that if there ends up being a bug in the way the runner's result is returned through HTML, it's possible that we could end up with a `"\n"` string rather than an empty string.

File: backend/LexBoxApi/Services/HgService.cs (hunk 2 above)
Comment (rmunn) [reply backend/LexBoxApi/Services/HgService.cs]: Handled in 075cd630.

**Review by hahn-kev — APPROVED** [review]

**Review by myieye — APPROVED** [review]

**Comment by hahn-kev** [comment]
feel free to ignore that test failure and merge, I've seen it on other PRs and it's been fixed in develop
