### PR TITLE
Make new entries appear in navigation list

### LINKED ISSUE #1327: after creating a new entry it does not show up in the entry list
**Describe the bug**
If you create an entry, it is created, however you can't see it and it doesn't show up in the list

**Expected behavior**
The entry should be selected and in the list of entries, not sure how we want to get it in there though, do we refresh the whole list of entries? if so it could be below the fold and then not included in the query.

### PR DESCRIPTION
**Pull request by rmunn**
Fixes #1327.

I have chosen to use the `{dontNavigate: true}` option when calling `onEntryCreated` so that the search bar won't be changed, because I found the UX of having other entries disappear from the left-side list to be confusing. I opened #1366 to track one idea I had for changing that UX.

### CODE REVIEW

File: frontend/viewer/src/ProjectView.svelte [hunk 1]
```diff
@@ -217,6 +217,8 @@
     $entries?.push(entry);//need to add it before refresh, otherwise it won't get selected because it's not in the list
     if (!options?.dontNavigate) {
```
Comment (hahn-kev) [inline frontend/viewer/src/ProjectView.svelte:218]: now that there's an else can we flip this condition? `if not don't navigate` is a double negative. If we flip this then it can just read `if don't navigate`

Comment (myieye) [reply frontend/viewer/src/ProjectView.svelte:218]: I think we could probably also just merge this, because we're going to revisit everything and I've suggested always refreshing (i.e. removing the `else`) in #1372:

> In the 2 cases "on new entry created by us" and "on new entry from a different user" we have the problem of knowing if the entry should be in the current filtered list of entries on our machine. I can think of 2 fixes:
> 1) Ultra-complex pro fix: we ask the server if entry X matches filter Y and what index it has in the matching result list, so we can insert it ourselves. Yikes.
> 2) Quick fix: we always just refresh the list of entries and it'll show up if it should. 👈 I'd be inclined to implement this as part of this issue.

**Review by myieye — APPROVED** [review]

File: frontend/viewer/src/ProjectView.svelte (hunk 1 above)
Comment (rmunn) [reply frontend/viewer/src/ProjectView.svelte:218]: Agree on merging this, and I'll add a note to #1372 mentioning wanting to flip the check (any time you see `if (!dontFoo)`, you should ask yourself whether you can make it `if (foo)` instead).
