### PR TITLE
make api to call fw headless sync

### LINKED ISSUE #1255: FwHeadless: CookieException when cookie domain has port number in it
**Describe the bug**

Running FwHeadless locally and trying to sync sena-3 resulted in a System.Net.CookieException saying "The `'Domain'='lexbox:5158'` part of the cookie is invalid.".

Removing the port from the cookie (by using `lexboxUrl.Host` in the Cookie constructor instead of `lexboxUrl.Authority`) worked. The `Authority` property is documented to contain the port only if the port is not the default port.

Don't have time to work on this right now, but we want to come back and revisit this at some point.

### PR DESCRIPTION
**Pull request by hahn-kev**
related to #1244 but does not close it
found bug #1251 while testing this
closes #1255 

adds an API for lexbox to call fw-headless sync, I also took the chance to test out the new service discovery package which standardizes configuring where http service host names are defined. See appsettings.Development.json and lexbox-deployment.yaml for how that's setup

### CODE REVIEW

File: backend/LexBoxApi/Controllers/CrdtController.cs [hunk 1]
```diff
@@ -85,4 +87,13 @@ public async Task<ActionResult<Guid>> GetProjectId(string code)
 
         return Ok(projectId);
     }
+
+    [HttpPost("crdt-sync/{projectId}")]
+    [AdminRequired]
```
Comment (myieye) [inline backend/LexBoxApi/Controllers/CrdtController.cs:92]: Is this perhaps a start for handling long syncs?
```suggestion
    [AdminRequired]
    [RequestTimeout(300_000)]
```

**Review by myieye — APPROVED** [review]
I pushed some changes and have some feedback that I think is worth looking at.
But, this is ultimately mergeable.

File: backend/LexBoxApi/Controllers/CrdtController.cs (hunk 1 above)
Comment (myieye) [reply backend/LexBoxApi/Controllers/CrdtController.cs:93]: By the way, I suggested 300s, because that's apparently the default `fetch()` timeout in Chrome.
In Firefox, it's apparently only 90s.

https://stackoverflow.com/a/62470009/2301416

**Review by myieye — APPROVED** [review]
Still LGTM
I resolved the conflicts.
